Repository AyuntamientoMadrid/consul, pull requests merged in 2018-12, with the labels that each got.

#1739 Check recipient of newsletter before resending
  app/models/newsletter.rb
  spec/models/newsletter_spec.rb
Labels: Backport Needed

#1660 Fix flaky spec: Legislation Proposals Each user has a different and consistent random proposals order
  app/controllers/legislation/processes_controller.rb
  spec/features/custom/legislation/proposals_spec.rb
  spec/features/legislation/proposals_spec.rb
Labels: Backport Needed

#1733 Add document uploads from admin section
  app/controllers/admin/site_customization/documents_controller.rb
  app/helpers/admin_helper.rb
  app/models/document.rb
  app/views/admin/_menu.html.erb
  app/views/admin/site_customization/documents/index.html.erb
  app/views/admin/site_customization/documents/new.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/routes/admin.rb
  db/migrate/20181128175808_add_admin_to_documents.rb
  db/schema.rb
  spec/factories/files.rb
  spec/features/admin/site_customization/documents_spec.rb
  spec/models/document_spec.rb
Labels: Backport Needed

#1740 Widgets dev seeds
  db/dev_seeds/widgets.rb
Labels: Backport Needed

#1741 [Upstream] Adds draft phase in legislation processes
  app/controllers/admin/legislation/processes_controller.rb
  app/controllers/legislation/processes_controller.rb
  app/models/legislation/process.rb
  app/views/admin/legislation/processes/_form.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  db/migrate/20181016204729_add_draft_phase_to_legislation_processes.rb
  db/schema.rb
  spec/factories/legislations.rb
  spec/features/admin/legislation/processes_spec.rb
  spec/features/legislation/processes_spec.rb
  spec/models/legislation/process/phase_spec.rb
  spec/models/legislation/process_spec.rb
Labels: Backport Needed

#1742 New algorithm for filter 'most active'
  app/models/debate.rb
  app/models/legislation/proposal.rb
  app/models/proposal.rb
  config/locales/en/settings.yml
  config/locales/es/general.yml
  config/locales/es/settings.yml
  db/dev_seeds/settings.rb
  db/seeds.rb
  lib/score_calculator.rb
  lib/tasks/settings.rake
  lib/tasks/votes.rake
  spec/models/debate_spec.rb
  spec/models/legislation/proposal_spec.rb
  spec/models/proposal_spec.rb
Labels: Backport Needed

#1750 Draft phase on legislation processes
  app/models/legislation/process.rb
  spec/models/legislation/process_spec.rb
Labels: Backport Needed

#1751 Fix proposal info rendering for managers
  app/views/custom/proposals/show.html.erb
  app/views/proposals/show.html.erb
Labels: Backport Needed

#1753 Refactor gender and age stats methods
  app/helpers/stats_helper.rb
  app/models/budget/stats.rb
  app/models/concerns/statisticable.rb
  app/models/poll/stats.rb
  app/views/polls/stats.html.erb
Labels: Backport Needed

#1704 Move "Toda la ciudad" code to custom files
  app/controllers/budgets/executions_controller.rb
  app/controllers/custom/budgets/executions_controller.rb
  app/helpers/budget_executions_helper.rb
  app/models/budget/investment.rb
Labels: Backport Needed

#1759 Most active score daily update
  config/schedule.rb
  lib/tasks/votes.rake
Labels: Backport Needed

#1758 Fix flaky spec checking price without currency symbol
  spec/features/budgets/investments_spec.rb
Labels: Backport Needed, Flaky spec

#1765 Enable useless assignment rubocop rule
  .rubocop_basic.yml
Labels: Backport Needed

#1760 Budget investments price explanation
  app/views/budgets/investments/_investment_show.html.erb
  config/locales/en/budgets.yml
  config/locales/es/budgets.yml
  spec/features/budgets/investments_spec.rb
Labels: Backport Needed

#1761 [Upstream] Add map to sidebar on Heading's page
  app/assets/stylesheets/layout.scss
  app/controllers/admin/budget_headings_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/models/budget/heading.rb
  app/views/admin/budgets/_heading_form.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/investments/_map.html.erb
  app/views/budgets/investments/_sidebar.html.erb
  config/locales/en/admin.yml
  config/routes/budget.rb
  db/dev_seeds/budgets.rb
  db/migrate/20181109111037_add_location_to_headings.rb
  db/schema.rb
  lib/migrate_spending_proposals_to_investments.rb
  spec/factories/budgets.rb
  spec/features/admin/budgets_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/tags/budget_investments_spec.rb
  spec/models/budget/heading_spec.rb
Labels: budget

#1764 Admin poll questions index
  app/views/admin/poll/questions/_questions.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/poll/questions_spec.rb
Labels: Backport Needed

#1766 Fix literal as condition
  .rubocop_basic.yml
  app/models/budget/investment.rb
Labels: Backport Needed

#1772 Honeypot on users sign up form
  app/controllers/users/registrations_controller.rb
  app/views/users/registrations/new.html.erb
  spec/features/registration_form_spec.rb
Labels: Backport Needed

#1773 Documents title
  app/views/documents/_documents.html.erb
  spec/shared/features/documentable.rb
Labels: Backport Needed

#1775 [Bug] [Management] Cannot create Budget Investment without map location
  app/controllers/management/budgets/investments_controller.rb
  spec/features/management/budget_investments_spec.rb
  spec/shared/features/mappable.rb
Labels: Backport Needed, Bug, admin

#1785 Add rubocop rule to indent private methods
  .rubocop_basic.yml
Labels: Backport Needed

#1781 Removes Legislation process custom documents
  app/models/legislation/process.rb
  app/views/custom/legislation/processes/proposals.html.erb
  app/views/legislation/processes/_custom_documents.html.erb
  app/views/legislation/processes/_documents_process_25.html.erb
  app/views/legislation/processes/_documents_process_26.html.erb
  app/views/legislation/processes/_documents_process_28.html.erb
  app/views/legislation/processes/_documents_process_29.html.erb
  app/views/legislation/processes/_documents_process_30.html.erb
  app/views/legislation/processes/debate.html.erb
  app/views/legislation/processes/phase_empty.html.erb
  app/views/legislation/processes/phase_not_open.html.erb
  app/views/legislation/processes/proposals.html.erb
  spec/features/legislation/processes_spec.rb
Labels: Backport Needed

#1754 Add gender and age stats to polls
  app/assets/images/stats_man.png
  app/assets/images/stats_woman.png
  app/assets/javascripts/application.js
  app/assets/javascripts/dropdown.js.coffee
  app/assets/javascripts/foundation_extras.js.coffee
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom/_polls_results_stats.scss
  app/assets/stylesheets/participation.scss
  app/assets/stylesheets/stats.scss
  app/helpers/stats_helper.rb
  app/models/concerns/statisticable.rb
  app/models/poll/stats.rb
  app/views/budgets/stats/show.html.erb
  app/views/polls/_poll_header.html.erb
  app/views/polls/stats.html.erb
  config/i18n-tasks.yml
  config/locales/custom/en/budgets.yml
  config/locales/custom/es/budgets.yml
  config/locales/en/general.yml
  config/locales/en/stats.yml
  config/locales/es/general.yml
  config/locales/es/stats.yml
  spec/models/budget/stats_spec.rb
Labels: Backport Needed

#1788 Removes arrow icon on active process phase
  app/assets/stylesheets/legislation_process.scss
Labels: Backport Needed
