Repository AyuntamientoMadrid/consul, pull requests merged in 2019-01, with the labels that each got.

#1774 LegacyLegislation processes migration (first phase)
  app/views/pages/processes/lobbies/additional.html
  app/views/pages/processes/lobbies/description.html
  app/views/pages/processes/lobbies/draft.html
  app/views/pages/processes/open_government/additional.html
  app/views/pages/processes/open_government/description.html
  app/views/pages/processes/open_government/draft.html
  app/views/pages/processes/service_letters/additional1.html
  app/views/pages/processes/service_letters/additional2.html
  app/views/pages/processes/service_letters/additional3.html
  app/views/pages/processes/service_letters/additional4.html
  app/views/pages/processes/service_letters/additional5.html
  app/views/pages/processes/service_letters/description1.html
  app/views/pages/processes/service_letters/description2.html
  app/views/pages/processes/service_letters/description3.html
  app/views/pages/processes/service_letters/description4.html
  app/views/pages/processes/service_letters/description5.html
  app/views/pages/processes/service_letters/draft1.html
  app/views/pages/processes/service_letters/draft2.html
  app/views/pages/processes/service_letters/draft3.html
  app/views/pages/processes/service_letters/draft4.html
  app/views/pages/processes/service_letters/draft5.html
  app/views/pages/processes/transparency/description.html
  app/views/pages/processes/transparency/draft.html
  lib/migrations/legacy_legislation/process.rb
  lib/tasks/legacy_legislation.rake
  spec/lib/migrations/legacy_legislation/process_spec.rb
Labels: Rake, legislation

#1782 LegacyLegislation processes annotations migration (second phase)
  lib/migrations/legacy_legislation/annotation.rb
  lib/tasks/legacy_legislation.rake
  spec/lib/migrations/legacy_legislation/annotation_spec.rb
Labels: Rake, legislation

#1787 Enable line length rubocop rule
  .rubocop.yml
  .rubocop_basic.yml
Labels: Backport Needed

#1791 Consider having valuator group as having valuator
  app/models/budget/investment.rb
  spec/features/admin/budget_investments_spec.rb
Labels: Backport Needed

#1797 Manage milestone progress bars
  app/assets/javascripts/forms.js.coffee
  app/assets/stylesheets/admin.scss
  app/controllers/admin/budget_investment_progress_bars_controller.rb
  app/controllers/admin/legislation/progress_bars_controller.rb
  app/controllers/admin/progress_bars_controller.rb
  app/controllers/admin/proposal_progress_bars_controller.rb
  app/models/concerns/milestoneable.rb
  app/models/progress_bar.rb
  app/models/progress_bar/translation.rb
  app/views/admin/legislation/progress_bars/index.html.erb
  app/views/admin/milestones/_milestones.html.erb
  app/views/admin/progress_bars/_form.html.erb
  app/views/admin/progress_bars/_progress_bars.html.erb
  app/views/admin/progress_bars/edit.html.erb
  app/views/admin/progress_bars/index.html.erb
  app/views/admin/progress_bars/new.html.erb
  config/initializers/foundation_rails_helper.rb
  config/initializers/routes_hierarchy.rb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  config/routes/admin.rb
  db/migrate/20190103132925_create_progress_bars.rb
  db/schema.rb
  spec/factories/budgets.rb
  spec/factories/milestones.rb
  spec/models/progress_bar_spec.rb
  spec/shared/features/admin_milestoneable.rb
  spec/shared/features/progressable.rb
Labels: Backport Needed

#1796 [Refactor] Delete duplicated tags <small> and be more consistent with consul repository
  app/views/admin/stats/proposal_notifications.html.erb
Labels: Improvement

#1793 [Cleanup] Remove unused code
  app/controllers/budgets/ballot/lines_controller.rb
Labels: Backport Needed

#1805 Refactor milestones css
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/milestones.scss
  app/assets/stylesheets/participation.scss
Labels: Backport Needed

#1798 Refactor poll stats methods
  app/models/poll/stats.rb
Labels: Backport Needed

#1795 [Improvement] CRUD budgets and content blocks
  app/helpers/admin_helper.rb
  app/views/admin/_menu.html.erb
  app/views/admin/budget_groups/index.html.erb
  app/views/admin/budget_headings/index.html.erb
  app/views/admin/site_customization/content_blocks/index.html.erb
  app/views/budgets/investments/_content_blocks.html.erb
  app/views/custom/layouts/_footer.html.erb
  app/views/layouts/_footer.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/budget_groups_spec.rb
  spec/features/admin/budget_headings_spec.rb
Labels: Backport Needed, Improvement

#1814 Enable double quotes rubocop rule
  .rubocop_basic.yml
Labels: Backport Needed

#1801 Legislation process homepage phase
  app/models/legislation/process.rb
  app/views/legislation/processes/_header.html.erb
  app/views/legislation/processes/_key_dates.html.erb
  app/views/legislation/processes/show.html.erb
  config/locales/en/legislation.yml
  config/locales/es/legislation.yml
  spec/features/legislation/processes_spec.rb
Labels: Backport Needed

#1825 Add custom styles and images for budget selecting phase
  app/assets/images/custom/budget_welcome/background_header.jpg
  app/assets/images/custom/welcome/background_header.jpg
  app/assets/images/custom/welcome/background_header_mobile.jpg
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/custom/_welcome.scss
  app/views/budgets/investments/_investment_show.html.erb
  app/views/custom/budgets/index.html.erb
  config/locales/custom/en/budgets.yml
  config/locales/custom/es/budgets.yml
  config/locales/en/budgets.yml
  public/social_media_budgets_2019_selecting.png
  public/social_media_budgets_2019_selecting_twitter.png
Labels: Backport Needed

#1813 Add progress bars to milestones public view
  app/assets/javascripts/forms.js.coffee
  app/assets/stylesheets/legislation_process.scss
  app/assets/stylesheets/milestones.scss
  app/helpers/milestones_helper.rb
  app/models/concerns/milestoneable.rb
  app/views/admin/shared/_common_globalize_locales.html.erb
  app/views/admin/shared/_globalize_tabs.html.erb
  app/views/legislation/processes/_key_dates.html.erb
  app/views/milestones/_milestones_content.html.erb
  app/views/milestones/_progress_bars.html.erb
  config/locales/en/milestones.yml
  config/locales/es/milestones.yml
  spec/features/legislation/processes_spec.rb
  spec/shared/features/admin_milestoneable.rb
  spec/shared/features/admin_progressable.rb
  spec/shared/features/milestoneable.rb
  spec/shared/features/progressable.rb
Labels: Backport Needed

#1832 Update budgets confirm group es translation
  config/locales/es/budgets.yml
Labels: Backport Needed

#1736 Add pending specs: Proposal Notifications Limits
  config/locales/en/activerecord.yml
  spec/features/proposal_notifications_spec.rb
  spec/models/proposal_notification_spec.rb
Labels: Backport Needed

#1826 Sort Legislation Processes by descending start date
  app/controllers/admin/legislation/processes_controller.rb
  app/controllers/legislation/processes_controller.rb
  app/models/legislation/process.rb
  spec/features/admin/legislation/processes_spec.rb
  spec/features/legislation/processes_spec.rb
Labels: Backport Needed

#1839 Allow change map image from admin
  app/assets/images/map.jpg
  app/models/site_customization/image.rb
  app/views/admin/site_customization/images/index.html.erb
  app/views/proposals/_geozones.html.erb
  spec/features/admin/site_customization/images_spec.rb
  spec/fixtures/files/custom_map.jpg
Labels: Backport Needed

#1831 Use find instead of find by id
  app/controllers/admin/budget_groups_controller.rb
  app/controllers/admin/budget_headings_controller.rb
  app/controllers/admin/budget_investments_controller.rb
  app/controllers/admin/budgets_controller.rb
  app/controllers/budgets/ballot/lines_controller.rb
  app/controllers/budgets/ballots_controller.rb
  app/controllers/budgets/executions_controller.rb
  app/controllers/budgets/groups_controller.rb
  app/controllers/budgets/investments_controller.rb
  app/controllers/budgets/recommendations_controller.rb
  app/controllers/budgets/results_controller.rb
  app/controllers/budgets/stats_controller.rb
  app/controllers/budgets_controller.rb
  app/controllers/management/budgets/investments_controller.rb
  app/controllers/related_contents_controller.rb
  app/controllers/valuation/budget_investments_controller.rb
  app/models/budget/investment.rb
  app/models/concerns/sluggable.rb
  config/routes/custom.rb
  spec/controllers/budgets/ballots/lines_controller_spec.rb
  spec/controllers/related_contents_controller_spec.rb
  spec/features/admin/budget_groups_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/budgets_spec.rb
  spec/features/budgets/ballots_spec.rb
  spec/features/budgets/budgets_spec.rb
  spec/features/budgets/executions_spec.rb
  spec/features/budgets/groups_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/budgets/recommendation_spec.rb
  spec/features/budgets/results_spec.rb
  spec/features/budgets/stats_spec.rb
  spec/features/management/budget_investments_spec.rb
  spec/features/valuation/budget_investments_spec.rb
  spec/models/budget/investment_spec.rb
Labels: Backport Needed, Improvement

#1841 Allow admins delete poll answer documents
  app/models/abilities/administrator.rb
  app/views/admin/poll/questions/answers/documents.html.erb
  spec/features/admin/poll/questions/answers/documents/documents_spec.rb
Labels: Backport Needed

#1851 Improve UI of budgets index page
  app/helpers/budgets_helper.rb
  app/views/budgets/index.html.erb
  app/views/budgets/investments/index.html.erb
  app/views/custom/budgets/index.html.erb
  app/views/custom/budgets/investments/index.html.erb
  spec/features/budgets/budgets_spec.rb
  spec/features/budgets/investments_spec.rb
Labels: Backport Needed

#1837 Admin polls list
  app/controllers/admin/poll/polls_controller.rb
  app/views/admin/poll/polls/_poll.html.erb
  app/views/admin/poll/polls/index.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/poll/polls_spec.rb
Labels: Backport Needed
