Repository AyuntamientoMadrid/consul, pull requests merged in 2019-05, with the labels that each got.

#1991 Sort investments by cached votes plus physical votes
  app/models/budget/investment.rb
  spec/models/budget/investment_spec.rb
Labels: Backport Needed, Budget, admin

#1992 Change devise configuration
  config/initializers/devise.rb
  spec/features/users_auth_spec.rb
Labels: Backport Needed

#1994 Fix investment order spec
  app/models/budget/investment.rb
Labels: Backport Needed

#1985 Remove deprecated translations code
  app/models/concerns/notifiable.rb
  app/models/notification.rb
  app/views/notifications/_notification.html.erb
  db/migrate/20190221154819_remove_deprecated_translatable_fields_from_banners.rb
  db/migrate/20190221162450_remove_deprecated_translatable_fields_from_polls.rb
  db/migrate/20190221162858_remove_deprecated_translatable_fields_from_poll_questions.rb
  db/migrate/20190221163818_remove_deprecated_translatable_fields_from_admin_notifications.rb
  db/migrate/20190221164056_remove_deprecated_translatable_fields_from_milestones.rb
  db/migrate/20190221164559_remove_deprecated_translatable_fields_from_legislation_draft_versions.rb
  db/migrate/20190221164928_remove_deprecated_translatable_fields_from_legislation_processes.rb
  db/migrate/20190221165347_remove_deprecated_translatable_fields_from_legislation_questions.rb
  db/migrate/20190221171155_remove_deprecated_translatable_fields_from_legislation_question_options.rb
  db/migrate/20190221171859_remove_deprecated_translatable_fields_from_site_customization_pages.rb
  db/migrate/20190221172209_remove_deprecated_translatable_fields_from_widget_cards.rb
  db/migrate/20190325184500_remove_deprecated_translatable_fields_from_budgets.rb
  db/migrate/20190325185046_remove_deprecated_translatable_fields_from_budget_groups.rb
  db/migrate/20190325185405_remove_deprecated_translatable_fields_from_budget_headings.rb
  db/migrate/20190325185550_remove_deprecated_translatable_fields_from_budget_phases.rb
  db/schema.rb
Labels: Backport Needed

#1996 Remove deprecated attributes from Poll::Question::Answer
  db/migrate/20190221163117_remove_deprecated_translatable_fields_from_poll_question_answers.rb
  db/schema.rb
Labels: Backport Needed

#1998 Fix obsolete `respond_with_bip` usage
  app/controllers/dashboard/polls_controller.rb
  spec/features/dashboard/polls_spec.rb
Labels: Backport Needed

#2002 Fix typo in budget executions spec
  spec/features/budgets/executions_spec.rb
Labels: Backport Needed

#2003 Remove unused (and flaky) card code and its spec
  app/models/widget/card.rb
  spec/models/widget/card_spec.rb
Labels: Backport Needed

#1997 Show reCAPTCHA after consecutive failed attempts
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/login_form.js.coffee
  app/assets/stylesheets/layout.scss
  app/controllers/users/sessions_controller.rb
  app/models/user.rb
  app/views/devise/sessions/new.html.erb
  config/i18n-tasks.yml
  config/initializers/devise.rb
  config/initializers/recaptcha.rb
  config/locales/en/devise.yml
  config/locales/en/settings.yml
  config/locales/es/devise.yml
  config/locales/es/settings.yml
  config/routes/devise.rb
  config/secrets.yml.example
  db/dev_seeds/settings.rb
  db/migrate/20190507102732_add_failed_attempts_to_users.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/settings.rake
  spec/features/users_auth_spec.rb
  spec/models/user_spec.rb
Labels: Backport Needed, security

#2001 Don't destroy budgets with an associated poll
  app/controllers/admin/budgets_controller.rb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/budgets_spec.rb
Labels: Backport Needed

#1989 Add options to show advanced stats
  app/controllers/admin/budgets_controller.rb
  app/controllers/admin/poll/polls_controller.rb
  app/controllers/concerns/report_attributes.rb
  app/controllers/dashboard/polls_controller.rb
  app/models/abilities/everyone.rb
  app/models/budget.rb
  app/models/concerns/reportable.rb
  app/models/concerns/statisticable.rb
  app/models/poll.rb
  app/models/report.rb
  app/views/admin/budgets/_form.html.erb
  app/views/admin/poll/results/_show_results.html.erb
  app/views/admin/shared/_show_results_fields.html.erb
  app/views/budgets/stats/_advanced_stats.html.erb
  app/views/budgets/stats/_advanced_stats_links.html.erb
  app/views/budgets/stats/show.html.erb
  app/views/polls/_advanced_stats.html.erb
  app/views/polls/_advanced_stats_links.html.erb
  app/views/polls/stats.html.erb
  config/i18n-tasks.yml
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/es/activerecord.yml
  config/locales/es/admin.yml
  db/migrate/20190424114803_create_reports.rb
  db/migrate/20190429125842_add_advanced_stats_to_reports.rb
  db/schema.rb
  lib/migrations/reports.rb
  lib/tasks/stats_and_results.rake
  spec/factories/budgets.rb
  spec/features/admin/budgets_spec.rb
  spec/features/budgets/executions_spec.rb
  spec/features/budgets/investments_spec.rb
  spec/features/budgets/results_spec.rb
  spec/features/budgets/stats_spec.rb
  spec/features/polls/polls_spec.rb
  spec/lib/migrations/reports_spec.rb
  spec/models/abilities/everyone_spec.rb
  spec/models/budget_spec.rb
  spec/models/concerns/reportable.rb
  spec/models/poll/poll_spec.rb
Labels: Backport Needed

#2006 Users menu
  app/helpers/users_helper.rb
  app/views/admin/shared/_admin_shortcuts.html.erb
  app/views/custom/layouts/_admin_header.html.erb
  app/views/custom/shared/_admin_login_items.html.erb
  app/views/layouts/_admin_header.html.erb
  app/views/layouts/management.html.erb
  app/views/shared/_admin_login_items.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/features/admin/budget_investments_spec.rb
  spec/features/management_spec.rb
  spec/features/officing_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/features/users_auth_spec.rb
  spec/support/common_actions/notifications.rb
Labels: Backport Needed

#2005 Improve help texts on Admin UI
  app/assets/images/logo_email.png
  app/mailers/application_mailer.rb
  app/models/site_customization/image.rb
  app/views/admin/budget_investments/_select_investment.html.erb
  app/views/admin/newsletters/new.html.erb
  app/views/admin/poll/officers/_search.html.erb
  app/views/admin/poll/shifts/_shifts.html.erb
  app/views/admin/site_customization/pages/_form.html.erb
  app/views/layouts/_mailer_header.html.erb
  config/locales/en/admin.yml
  config/locales/en/community.yml
  config/locales/en/documents.yml
  config/locales/en/images.yml
  config/locales/es/admin.yml
  spec/features/admin/budget_groups_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/budgets_spec.rb
  spec/features/admin/poll/polls_spec.rb
  spec/features/admin/poll/shifts_spec.rb
  spec/features/admin/site_customization/images_spec.rb
  spec/features/admin/tags_spec.rb
  spec/features/topics_specs.rb
  spec/fixtures/files/logo_email_custom.png
  spec/shared/features/documentable.rb
Labels: Backport Needed

#1745 Proposals support on mobile
  app/assets/javascripts/foundation_extras.js.coffee
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/participation.scss
  app/views/custom/proposals/show.html.erb
  app/views/proposals/show.html.erb
  spec/features/proposals_spec.rb
Labels: Backport Needed

#2014 Remove Rspec deprecation warning
  spec/controllers/users/confirmations_controller_spec.rb
Labels: Backport Needed

#2018 Resize Capybara window back to its original size
  spec/features/proposals_spec.rb
Labels: Backport Needed

#2017 Generate navigation links for polls without a slug
  app/helpers/polls_helper.rb
  app/views/polls/_poll_subnav.html.erb
  spec/features/polls/polls_spec.rb
Labels: upstream

#1746 Simplify settings seeds
  app/models/setting.rb
  db/dev_seeds/settings.rb
  db/seeds.rb
Labels: Backport Needed

#2027 Fix valid votes labels
  app/controllers/admin/poll/recounts_controller.rb
  app/helpers/poll_recounts_helper.rb
  app/models/poll/stats.rb
  app/views/admin/poll/recounts/index.html.erb
  config/locales/en/admin.yml
  config/locales/en/officing.yml
  config/locales/es/admin.yml
  config/locales/es/officing.yml
  spec/features/admin/poll/polls_spec.rb
  spec/helpers/poll_recounts_helper_spec.rb
Labels: Backport Needed

#1995 Hide polls created by users from proposals dashboard on admin poll index
  app/controllers/admin/poll/polls_controller.rb
  app/models/poll.rb
  spec/features/admin/poll/polls_spec.rb
Labels: Backport Needed

#2019 Add help texs, links and new message section to improve UX
  app/assets/stylesheets/legislation.scss
  app/assets/stylesheets/legislation_process.scss
  app/controllers/dashboard_controller.rb
  app/helpers/proposals_dashboard_helper.rb
  app/views/comments/_comment.html.erb
  app/views/communities/show.html.erb
  app/views/custom/legislation/proposals/show.html.erb
  app/views/custom/proposals/index.html.erb
  app/views/dashboard/_menu.html.erb
  app/views/dashboard/messages.html.erb
  app/views/legislation/proposals/show.html.erb
  app/views/proposals/_proposals_lists.html.erb
  app/views/proposals/index.html.erb
  config/locales/en/general.yml
  config/locales/en/legislation.yml
  config/locales/en/settings.yml
  config/locales/es/general.yml
  config/locales/es/legislation.yml
  config/locales/es/settings.yml
  config/routes/proposal.rb
  spec/features/comments/budget_investments_spec.rb
  spec/features/comments/budget_investments_valuation_spec.rb
  spec/features/comments/debates_spec.rb
  spec/features/comments/legislation_annotations_spec.rb
  spec/features/comments/legislation_questions_spec.rb
  spec/features/comments/polls_spec.rb
  spec/features/comments/proposals_spec.rb
  spec/features/comments/topics_spec.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/features/legislation/proposals_spec.rb
  spec/features/proposal_notifications_spec.rb
  spec/features/proposals_spec.rb
  spec/support/common_actions/notifications.rb
Labels: Backport Needed

#2022 Extract partial with mobile sticky content
  app/views/custom/proposals/show.html.erb
  app/views/proposals/_support_status.html.erb
  app/views/proposals/show.html.erb
Labels: Backport Needed

#2023 Allow users to delete dashboard polls
  app/controllers/admin/poll/polls_controller.rb
  app/controllers/dashboard/polls_controller.rb
  app/models/poll.rb
  app/models/poll/question.rb
  app/views/dashboard/polls/_form.html.erb
  app/views/dashboard/polls/_poll.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  config/routes/proposal.rb
  spec/features/admin/poll/polls_spec.rb
  spec/features/dashboard/polls_spec.rb
Labels: Backport Needed

#2025 Add new settings automatically on every deployment
  app/models/setting.rb
  config/deploy.rb
  lib/tasks/settings.rake
  spec/models/setting_spec.rb
Labels: Backport Needed
