Repository AyuntamientoMadrid/consul, pull requests merged in 2019-04, with the labels that each got.

#1935 Show only existing stats
  app/controllers/budgets/stats_controller.rb
  app/controllers/polls_controller.rb
  app/models/budget/stats.rb
  app/models/concerns/statisticable.rb
  app/models/poll/stats.rb
  app/views/budgets/stats/show.html.erb
  app/views/polls/stats.html.erb
  app/views/shared/stats/_age.html.erb
  app/views/shared/stats/_gender.html.erb
  app/views/shared/stats/_geozone.html.erb
  app/views/shared/stats/_links.html.erb
  app/views/shared/stats/_participation.html.erb
  config/locales/en/stats.yml
  config/locales/es/stats.yml
  spec/models/budget/stats_spec.rb
  spec/models/poll/stats_spec.rb
  spec/models/statisticable_spec.rb
Labels: Backport Needed, stats

#1946 Fix sort by random inconsistencies
  app/models/concerns/randomizable.rb
Labels: Backport Needed

#1940 Show budget stats for finished phases
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/stats.scss
  app/models/abilities/administrator.rb
  app/models/abilities/everyone.rb
  app/models/budget.rb
  app/models/budget/phase.rb
  app/models/budget/stats.rb
  app/views/budgets/stats/show.html.erb
  config/i18n-tasks.yml
  config/locales/en/stats.yml
  config/locales/es/stats.yml
  spec/features/budgets/stats_spec.rb
  spec/models/budget/phase_spec.rb
  spec/models/budget/stats_spec.rb
  spec/models/budget_spec.rb
Labels: Backport Needed, stats

#1948 Fix investment pagination tests
  spec/features/budgets/investments_spec.rb
Labels: upstream

#1950 Include hidden users in stats
  app/models/budget/stats.rb
  app/models/concerns/statisticable.rb
  app/models/poll/stats.rb
  spec/models/budget/stats_spec.rb
  spec/models/poll/stats_spec.rb
Labels: Backport Needed, stats

#1961 Fix exception when confirming an invalid token
  app/controllers/users/confirmations_controller.rb
  spec/controllers/users/confirmations_controller_spec.rb
Labels: upstream

#1963 Increase poll stats performance
  app/models/poll/stats.rb
Labels: stats

#1966 Fix legacy use of poll stats
  app/models/poll/question/answer.rb
  app/views/polls/_stats_2018.html.erb
Labels: Backport Needed

#1938 Add rake task to check for spending proposals
  lib/tasks/spending_proposals.rake
Labels: Backport Needed, Budget, Spending Proposals

#1955 Fix pagination after selecting/unselecting budget investment
  app/views/admin/budget_investments/_investments.html.erb
  app/views/admin/budget_investments/_select_investment.html.erb
  app/views/admin/budget_investments/toggle_selection.js.erb
  spec/features/admin/budget_investments_spec.rb
Labels: Budget, Bug, admin

#1959 Fix bug moderator can't print voted investments in balloting phase
  app/helpers/application_helper.rb
  app/views/budgets/investments/_investment.html.erb
  spec/features/management/budget_investments_spec.rb
  spec/support/common_actions/users.rb
Labels: Budget, Bug, admin

#1970 Update share messages interpolation variables
  config/locales/ar/budgets.yml
  config/locales/de-DE/budgets.yml
  config/locales/gl/budgets.yml
  config/locales/gl/general.yml
  config/locales/nl/budgets.yml
  config/locales/ru/general.yml
  config/locales/so-SO/budgets.yml
  config/locales/so-SO/general.yml
  config/locales/sq-AL/budgets.yml
  config/locales/sq-AL/general.yml
  config/locales/val/budgets.yml
  config/locales/val/general.yml
  config/locales/zh-CN/budgets.yml
  config/locales/zh-CN/general.yml
Labels: Backport Needed

#1973 Remove custom poll group view
  app/helpers/custom/polls_helper.rb
  app/helpers/polls_helper.rb
  app/views/custom/polls/_poll_group.html.erb
  app/views/polls/_poll_group.html.erb
Labels: Backport Needed

#1975 Update recent model and migration files
  app/controllers/admin/poll/polls_controller.rb
  app/models/stats_version.rb
  db/migrate/20190311215516_destroy_spending_proposals.rb
  db/migrate/20190311220350_destroy_spending_proposal_ballots.rb
  db/migrate/20190311220600_destroy_spending_proposal_delegation.rb
  db/migrate/20190311220711_destroy_spending_proposal_valuations.rb
  db/migrate/20190326210351_destroy_spending_proposal_supports.rb
  db/migrate/20190326211832_destroy_spending_proposal_associations.rb
  db/migrate/20190408133956_create_stats_versions.rb
Labels: Backport Needed

#1976 Handle AccessDenied in management sessions
  app/controllers/application_controller.rb
  app/controllers/concerns/access_denied_handler.rb
  app/controllers/management/sessions_controller.rb
  spec/controllers/management/sessions_controller_spec.rb
Labels: Backport Needed

#1977 Fix InvalidCrossOriginRequest response
  app/controllers/pages_controller.rb
  spec/controllers/pages_controller_spec.rb
Labels: Backport Needed

#1980 Fix flaky spec: Ballots Groups Change my heading
  spec/features/budgets/ballots_spec.rb
Labels: Backport Needed

#1981 Regenerate schema file
  db/schema.rb
Labels: Backport Needed

#1982 Dashboard UI improvements
  app/assets/stylesheets/dashboard.scss
  app/controllers/admin/dashboard/actions_controller.rb
  app/helpers/admin/proposal_dashboard_actions_helper.rb
  app/helpers/proposals_dashboard_helper.rb
  app/views/admin/dashboard/actions/_form.html.erb
  app/views/communities/_poll.html.erb
  app/views/communities/show.html.erb
  app/views/custom/proposals/show.html.erb
  app/views/dashboard/_goal.html.erb
  app/views/dashboard/_resource.html.erb
  app/views/proposals/created.html.erb
  app/views/proposals/share.html.erb
  app/views/users/_proposal.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  lib/tasks/proposal_actions.rake
Labels: Backport Needed

#1983 Add message on dashboard request to archived proposals
  app/views/dashboard/_form.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/features/dashboard/dashboard_spec.rb
Labels: Backport Needed

#1984 Polish Rails 5 and dashboard integration
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/best_in_place_initialize.js.coffee
  app/controllers/admin/poll/polls_controller.rb
  app/helpers/map_locations_helper.rb
  app/models/administrator_task.rb
  app/models/budget/group.rb
  app/models/dashboard/action.rb
  app/models/dashboard/administrator_task.rb
  app/models/dashboard/executed_action.rb
  app/models/link.rb
  app/views/dashboard/polls/_poll.html.erb
  config/environments/test.rb
  db/migrate/20180606085420_add_published_at_to_proposal.rb
  db/migrate/20180611072816_create_proposal_dashboard_actions.rb
  db/migrate/20180612072003_add_action_type_to_proposal_dashboard_actions.rb
  db/migrate/20180614122630_create_proposal_executed_dashboard_actions.rb
  db/migrate/20180615102215_create_administrator_tasks.rb
  db/migrate/20180625075520_add_related_to_polls.rb
  db/migrate/20180702050717_add_short_description_to_proposal_dashboard_actions.rb
  db/migrate/20180702060913_create_links.rb
  db/migrate/20180702085737_remove_comments_from_proposal_executed_dashboard_action.rb
  db/migrate/20180723084734_rename_proposal_dashboard_actions_to_dashboard_actions.rb
  db/migrate/20180723084804_rename_proposal_executed_dashboard_actions_to_dashboard_executed_actions.rb
  db/migrate/20180723102010_rename_administrator_task_to_dashboard_administrator_task.rb
  db/migrate/20180723112930_rename_dashboard_action_id_to_action_id.rb
  db/migrate/20180726055120_add_timestamps_to_dashboard_actions.rb
  db/migrate/20190108133246_add_published_proposal_to_dashboard_actions.rb
  db/migrate/20190411090023_remove_open_in_new_tab_from_links.rb
  spec/spec_helper.rb
Labels: Backport Needed

#1988 Fix obsolete reference to proposal question
  app/views/admin/poll/questions/_successful_proposals.html.erb
  spec/features/admin/poll/questions_spec.rb
Labels: Backport Needed

#1990 Proposals authors user segment
  app/views/admin/newsletters/show.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  lib/user_segments.rb
  spec/lib/user_segments_spec.rb
Labels: Backport Needed
