Repository AyuntamientoMadrid/consul, pull requests merged in 2019-03, with the labels that each got.

#1899 Add CoffeeLint rules
  .coffeelint.json
  .hound.yml
  app/assets/javascripts/banners.js.coffee
  app/assets/javascripts/check_all_none.js.coffee
  app/assets/javascripts/checkbox_toggle.js.coffee
  app/assets/javascripts/custom/probe.js.coffee
  app/assets/javascripts/globalize.js.coffee
  app/assets/javascripts/investment_report_alert.js.coffee
  app/assets/javascripts/legislation_annotatable.js.coffee
  app/assets/javascripts/location_changer.js.coffee
  app/assets/javascripts/map.js.coffee
  app/assets/javascripts/polls.js.coffee
  app/assets/javascripts/polls_admin.js.coffee
  app/assets/javascripts/prevent_double_submission.js.coffee
  app/assets/javascripts/send_admin_notification_alert.js.coffee
  app/assets/javascripts/send_newsletter_alert.js.coffee
  app/assets/javascripts/social_share.js.coffee
  app/assets/javascripts/sortable.js.coffee
  app/assets/javascripts/stats.js.coffee
  app/assets/javascripts/suggest.js.coffee
  app/assets/javascripts/table_sortable.js.coffee
  app/assets/javascripts/tag_autocomplete.js.coffee
  app/assets/javascripts/tracks.js.coffee
  app/assets/javascripts/tree_navigator.js.coffee
  app/assets/javascripts/valuation_budget_investment_form.js.coffee
  app/assets/javascripts/valuation_spending_proposal_form.js.coffee
  coffeelint.json
Labels: Backport Needed

#1900 Use double quotes in CoffeeScript files
  app/assets/javascripts/advanced_search.js.coffee
  app/assets/javascripts/allow_participation.js.coffee
  app/assets/javascripts/annotatable.js.coffee
  app/assets/javascripts/banners.js.coffee
  app/assets/javascripts/check_all_none.js.coffee
  app/assets/javascripts/checkbox_toggle.js.coffee
  app/assets/javascripts/comments.js.coffee
  app/assets/javascripts/documentable.js.coffee
  app/assets/javascripts/embed_video.js.coffee
  app/assets/javascripts/fixed_bar.js.coffee
  app/assets/javascripts/flaggable.js.coffee
  app/assets/javascripts/followable.js.coffee
  app/assets/javascripts/forms.js.coffee
  app/assets/javascripts/gettext.js.coffee
  app/assets/javascripts/globalize.js.coffee
  app/assets/javascripts/ie_alert.js.coffee
  app/assets/javascripts/imageable.js.coffee
  app/assets/javascripts/investment_report_alert.js.coffee
  app/assets/javascripts/legislation.js.coffee
  app/assets/javascripts/legislation_admin.js.coffee
  app/assets/javascripts/legislation_allegations.js.coffee
  app/assets/javascripts/legislation_annotatable.js.coffee
  app/assets/javascripts/location_changer.js.coffee
  app/assets/javascripts/managers.js.coffee
  app/assets/javascripts/map.js.coffee
  app/assets/javascripts/markdown_editor.js.coffee
  app/assets/javascripts/polls.js.coffee
  app/assets/javascripts/polls_admin.js.coffee
  app/assets/javascripts/prevent_double_submission.js.coffee
  app/assets/javascripts/send_admin_notification_alert.js.coffee
  app/assets/javascripts/send_newsletter_alert.js.coffee
  app/assets/javascripts/social_share.js.coffee
  app/assets/javascripts/sortable.js.coffee
  app/assets/javascripts/stats.js.coffee
  app/assets/javascripts/suggest.js.coffee
  app/assets/javascripts/table_sortable.js.coffee
  app/assets/javascripts/tag_autocomplete.js.coffee
  app/assets/javascripts/tags.js.coffee
  app/assets/javascripts/tracks.js.coffee
  app/assets/javascripts/tree_navigator.js.coffee
  app/assets/javascripts/users.js.coffee
  app/assets/javascripts/valuation_budget_investment_form.js.coffee
  app/assets/javascripts/valuation_spending_proposal_form.js.coffee
  app/assets/javascripts/votes.js.coffee
  app/assets/javascripts/watch_form_changes.js.coffee
Labels: Backport Needed

#1903 Show unfeasible budget investment messages only when valuation finished
  app/views/budgets/investments/_investment_show.html.erb
  spec/features/budgets/investments_spec.rb
Labels: Backport Needed

#1904 [Upstream] Show results checkbox for voted polls
  app/views/admin/poll/results/index.html.erb
  spec/factories/polls.rb
  spec/features/admin/poll/polls_spec.rb
Labels: admin, polls

#1910 Update spending proposals results url
  app/controllers/budgets/results_controller.rb
  app/views/custom/budgets/index.html.erb
  spec/features/budgets/results_spec.rb
Labels: Backport Needed, Budget, Spending Proposals

#1911 Expire budget investments' stats cache
  app/models/budget/stats.rb
Labels: Backport Needed, Budget, Spending Proposals

#1905 Migrate special supports and votes
  app/models/budget/ballot/line.rb
  lib/migrations/spending_proposal/ballot.rb
  lib/migrations/spending_proposal/vote.rb
  spec/lib/migrations/spending_proposals/ballot_spec.rb
  spec/lib/migrations/spending_proposals/delegated_ballot_spec.rb
  spec/lib/migrations/spending_proposals/vote_spec.rb
  spec/models/budget/ballot/line_spec.rb
Labels: Backport Needed, Budget, Spending Proposals

#1908 Order headings by name and group
  app/controllers/budgets/results_controller.rb
  app/controllers/budgets/stats_controller.rb
  app/views/budgets/results/show.html.erb
  app/views/budgets/stats/show.html.erb
  spec/features/budgets/results_spec.rb
  spec/features/budgets/stats_spec.rb
Labels: Backport Needed, Budget, Spending Proposals

#1909 Spending proposals pre and post migration actions
  lib/migrations/spending_proposal/budget.rb
  lib/tasks/spending_proposals.rake
  spec/lib/migrations/spending_proposals/budget_spec.rb
Labels: Backport Needed, Budget, Spending Proposals

#1898 Default site customization pages
  app/assets/javascripts/ckeditor/config.js
  app/controllers/welcome_controller.rb
  app/views/custom/pages/accessibility.html.erb
  app/views/custom/pages/conditions.html.erb
  app/views/custom/pages/help/faq/index.html.erb
  app/views/custom/pages/privacy.html.erb
  app/views/pages/accessibility.html.erb
  app/views/pages/conditions.html.erb
  app/views/pages/help/faq/index.html.erb
  app/views/pages/privacy.html.erb
  app/views/welcome/welcome.html.erb
  config/i18n-tasks.yml
  config/locales/custom/es/general.yml
  config/locales/en/general.yml
  config/locales/en/pages.yml
  config/locales/es/general.yml
  config/locales/es/pages.yml
  config/routes/custom.rb
  db/custom_pages.rb
  db/pages.rb
  db/pages/accessibility.rb
  db/pages/conditions.rb
  db/pages/custom/accessibility.rb
  db/pages/custom/conditions.rb
  db/pages/custom/faq.rb
  db/pages/custom/html/accessibility.html
  db/pages/custom/html/conditions.html
  db/pages/custom/html/faq.html
  db/pages/custom/html/privacy.html
  db/pages/custom/privacy.rb
  db/pages/faq.rb
  db/pages/privacy.rb
  db/pages/welcome_level_three_verified.rb
  db/pages/welcome_level_two_verified.rb
  db/pages/welcome_not_verified.rb
  db/seeds.rb
  lib/admin_wysiwyg_sanitizer.rb
  lib/tasks/db.rake
  public/logo_wcag1AA.gif
  public/marca_aenor.png
  spec/controllers/pages_controller_spec.rb
  spec/controllers/welcome_controller_spec.rb
  spec/features/admin/site_customization/pages_spec.rb
  spec/features/admin/widgets/cards_spec.rb
  spec/features/site_customization/custom_pages_spec.rb
  spec/features/welcome_spec.rb
  spec/lib/admin_wysiwyg_sanitizer_spec.rb
  spec/lib/tasks/db_spec.rb
Labels: Backport Needed, admin

#1919 Display all polls for current booth
  app/controllers/officing/voters_controller.rb
  app/models/poll.rb
  app/views/officing/voters/_already_voted.html.erb
  app/views/officing/voters/_cannot_vote.html.erb
  app/views/officing/voters/new.html.erb
  config/locales/en/officing.yml
  config/locales/es/officing.yml
  spec/features/officing/voters_spec.rb
Labels: Backport Needed, polls

#1776 Migrate spending proposal
  app/controllers/budgets/results_controller.rb
  app/controllers/budgets/stats_controller.rb
  app/controllers/spending_proposals_controller.rb
  app/models/budget/ballot/line.rb
  app/models/budget/stats.rb
  app/models/comment.rb
  app/models/spending_proposal.rb
  app/views/budgets/results/show.html.erb
  app/views/budgets/stats/show.html.erb
  app/views/custom/budgets/index.html.erb
  db/migrate/20190116152624_add_delegated_to_votes.rb
  db/schema.rb
  lib/migrations/log.rb
  lib/migrations/spending_proposal/ballot.rb
  lib/migrations/spending_proposal/ballots.rb
  lib/migrations/spending_proposal/budget.rb
  lib/migrations/spending_proposal/budget_investment.rb
  lib/migrations/spending_proposal/budget_investments.rb
  lib/migrations/spending_proposal/delegated_ballot.rb
  lib/migrations/spending_proposal/delegated_ballots.rb
  lib/migrations/spending_proposal/vote.rb
  lib/tasks/spending_proposals.rake
  spec/factories/custom.rb
  spec/features/budgets/executions_spec.rb
  spec/features/budgets/results_spec.rb
  spec/features/budgets/stats_spec.rb
  spec/features/spending_proposals_spec.rb
  spec/lib/migrations/spending_proposals/ballot_spec.rb
  spec/lib/migrations/spending_proposals/ballots_spec.rb
  spec/lib/migrations/spending_proposals/budget_investment_spec.rb
  spec/lib/migrations/spending_proposals/budget_investments_spec.rb
  spec/lib/migrations/spending_proposals/budget_spec.rb
  spec/lib/migrations/spending_proposals/delegated_ballot_spec.rb
  spec/lib/migrations/spending_proposals/delegated_ballots_spec.rb
  spec/lib/migrations/spending_proposals/vote_spec.rb
  spec/models/budget/ballot/line_spec.rb
  spec/models/spending_proposal_spec.rb
  spec/support/common_actions/budgets.rb
Labels: Budget, Spending Proposals

#1907 Fix accessibility and HTML warnings
  app/assets/stylesheets/layout.scss
  app/views/ballots/_ballot.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/investments/_votes.html.erb
  app/views/custom/budgets/index.html.erb
  app/views/custom/legislation/proposals/show.html.erb
  app/views/custom/welcome/index.html.erb
  app/views/debates/show.html.erb
  app/views/layouts/_tracking_page.html.erb
  app/views/legislation/processes/_header.html.erb
  app/views/legislation/proposals/_featured_votes.html.erb
  app/views/legislation/proposals/_votes.html.erb
  app/views/legislation/proposals/show.html.erb
  app/views/polls/_poll_header.html.erb
  app/views/proposals/_featured_votes.html.erb
  app/views/proposals/_info.html.erb
  app/views/proposals/_social_share.html.erb
  app/views/proposals/share.html.erb
  app/views/shared/_search_form.html.erb
  app/views/shared/_social_share.html.erb
  app/views/users/_ballot.html.erb
  app/views/users/_budget_investments.html.erb
  app/views/users/_comments.html.erb
  app/views/users/_debates.html.erb
  app/views/users/_proposals.html.erb
  config/locales/custom/en/general.yml
  config/locales/custom/es/general.yml
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/features/tracks_spec.rb
Labels: Backport Needed

#1929 Add ERB Lint configuration file
  .erb-lint.yml
  .hound.yml
  Gemfile
  Gemfile.lock
Labels: Backport Needed

#1930 Enable rubocop rules in config and seed files
  .rubocop_basic.yml
Labels: Backport Needed

#1936 Expire stats cache
  app/models/budget/stats.rb
Labels: Backport Needed, Budget, Spending Proposals

#1931 Simplify poll factories
  spec/factories/polls.rb
  spec/features/admin/poll/polls_spec.rb
  spec/models/poll/poll_spec.rb
  spec/models/poll/stats_spec.rb
  spec/models/poll/voter_spec.rb
Labels: Backport Needed

#1918 Improve Admin settings section
  app/assets/javascripts/application.js
  app/assets/javascripts/settings.js.coffee
  app/controllers/admin/settings_controller.rb
  app/controllers/admin/site_customization/content_blocks_controller.rb
  app/controllers/concerns/feature_flags.rb
  app/controllers/users_controller.rb
  app/helpers/feeds_helper.rb
  app/helpers/map_locations_helper.rb
  app/helpers/settings_helper.rb
  app/models/setting.rb
  app/models/widget/feed.rb
  app/views/admin/settings/_configuration_settings_tab.html.erb
  app/views/admin/settings/_featured_settings_table.html.erb
  app/views/admin/settings/_features_tab.html.erb
  app/views/admin/settings/_filter_subnav.html.erb
  app/views/admin/settings/_map_configuration_tab.html.erb
  app/views/admin/settings/_map_form.html.erb
  app/views/admin/settings/_participation_processes_tab.html.erb
  app/views/admin/settings/_settings_table.html.erb
  app/views/admin/settings/index.html.erb
  app/views/admin/site_customization/content_blocks/index.html.erb
  app/views/custom/layouts/devise.html.erb
  app/views/custom/layouts/landing.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/devise.html.erb
  app/views/layouts/nvotes.html.erb
  app/views/management/_menu.html.erb
  config/locales/en/admin.yml
  config/locales/en/settings.yml
  config/locales/es/admin.yml
  config/locales/es/settings.yml
  db/dev_seeds/budgets.rb
  db/dev_seeds/settings.rb
  db/seeds.rb
  lib/tasks/settings.rake
  spec/features/admin/budget_groups_spec.rb
  spec/features/admin/budget_headings_spec.rb
  spec/features/admin/budget_investments_spec.rb
  spec/features/admin/budgets_spec.rb
  spec/features/admin/debates_spec.rb
  spec/features/admin/feature_flags_spec.rb
  spec/features/admin/hidden_budget_investments_spec.rb
  spec/features/admin/hidden_proposals_spec.rb
  spec/features/admin/homepage/homepage_spec.rb
  spec/features/admin/legislation/draft_versions_spec.rb
  spec/features/admin/legislation/processes_spec.rb
  spec/features/admin/legislation/questions_spec.rb
  spec/features/admin/settings_spec.rb
  spec/features/comments/budget_investments_valuation_spec.rb
  spec/features/debates_spec.rb
  spec/features/emails_spec.rb
  spec/features/moderation/budget_investments_spec.rb
  spec/features/moderation/debates_spec.rb
  spec/features/moderation/proposals_spec.rb
  spec/features/proposals_spec.rb
  spec/features/users_spec.rb
  spec/features/valuation/budget_investments_spec.rb
  spec/features/valuation/budgets_spec.rb
  spec/lib/tasks/settings_spec.rb
  spec/models/setting_spec.rb
Labels: Backport Needed, Improvement, admin, ux

#1928 Require logged in user if navigate to /welcome
  app/controllers/welcome_controller.rb
  spec/features/welcome_spec.rb
Labels: Bug

#1914 Add rake to move external_url to description
  lib/tasks/proposals.rake
  spec/lib/tasks/proposals_spec.rb
Labels: Backport Needed

#1913 Remove question and external_url fields from proposals and legislation proposals
  app/controllers/legislation/proposals_controller.rb
  app/controllers/management/proposals_controller.rb
  app/controllers/proposals_controller.rb
  app/models/legislation/proposal.rb
  app/models/proposal.rb
  app/views/admin/hidden_proposals/index.html.erb
  app/views/custom/legislation/proposals/show.html.erb
  app/views/documents/_additional_documents.html.erb
  app/views/legislation/proposals/show.html.erb
  app/views/proposals/_form.html.erb
  app/views/proposals/_info.html.erb
  config/api.yml
  config/locales/en/documents.yml
  config/locales/en/general.yml
  config/locales/es/documents.yml
  config/locales/es/general.yml
  db/dev_seeds/legislation_proposals.rb
  db/dev_seeds/proposals.rb
  db/migrate/20190307165132_remove_question_and_external_url_from_proposals.rb
  db/migrate/20190307165337_remove_question_and_external_url_from_legislation_proposals.rb
  db/schema.rb
  spec/factories/proposals.rb
  spec/features/admin/hidden_proposals_spec.rb
  spec/features/api/csv_exporter_spec.rb
  spec/features/management/proposals_spec.rb
  spec/features/proposals_spec.rb
  spec/features/tags/proposals_spec.rb
  spec/models/proposal_spec.rb
  spec/support/common_actions.rb
  spec/support/common_actions/proposals.rb
Labels: Backport Needed

#1941 Remove deprecated task proposals spec
  spec/lib/tasks/proposals_spec.rb
Labels: Backport Needed

#1917 Remove deprecated settings
  app/controllers/proposals_controller.rb
  app/helpers/verification_helper.rb
  app/models/user.rb
  app/models/verification/residence.rb
  app/views/admin/stats/show.html.erb
  app/views/custom/proposals/_kit_decide.html.erb
  app/views/proposals/share.html.erb
  app/views/verification/residence/new.html.erb
  config/locales/custom/en/general.yml
  config/locales/custom/es/general.yml
  config/locales/en/general.yml
  config/locales/en/settings.yml
  config/locales/es/general.yml
  config/locales/es/settings.yml
  db/dev_seeds/settings.rb
  db/seeds.rb
  lib/tasks/settings.rake
  spec/features/proposals_spec.rb
  spec/features/verification/residence_spec.rb
Labels: Backport Needed

#1942 Remove obsolete rake tasks
  lib/tasks/budgets.rake
  lib/tasks/communities.rake
  lib/tasks/globalize.rake
  lib/tasks/homepage.rake
  lib/tasks/legislation.rake
  lib/tasks/locales.rake
  lib/tasks/map_locations.rake
  lib/tasks/migrate_milestones_and_statuses.rake
  lib/tasks/polls.rake
  lib/tasks/polls_slugs.rake
  lib/tasks/polls_stats_2018.rake
  lib/tasks/probe_plaza.rake
  lib/tasks/settings.rake
  lib/tasks/slugs.rake
  lib/tasks/stats.rake
  lib/tasks/users.rake
  lib/tasks/web_sections.rake
  spec/lib/tasks/communities_spec.rb
  spec/lib/tasks/globalize_spec.rb
  spec/lib/tasks/map_location_spec.rb
  spec/lib/tasks/milestones_spec.rb
  spec/lib/tasks/settings_spec.rb
Labels: Backport Needed

#1943 Fix legislation process feed order
  app/models/widget/feed.rb
Labels: upstream

#1934 Include default custom pages in developers seed
  db/dev_seeds.rb
  db/dev_seeds/pages.rb
Labels: Backport Needed
