Repository AyuntamientoMadrid/consul, pull requests merged in 2019-06, with the labels that each got.

#2029 Avoid duplicate records using translations
  app/controllers/polls_controller.rb
  app/controllers/valuation/budget_investments_controller.rb
  app/models/budget/group.rb
  app/models/budget/heading.rb
  app/models/poll.rb
  app/models/poll/booth.rb
  app/models/user.rb
  app/views/budgets/investments/_votes.html.erb
  spec/models/budget/group_spec.rb
  spec/models/budget/heading_spec.rb
  spec/models/poll/booth_spec.rb
  spec/models/poll/poll_spec.rb
  spec/models/user_spec.rb
Labels: Backport Needed

#2008 Images and documents settings
  app/assets/stylesheets/admin.scss
  app/controllers/admin/settings_controller.rb
  app/helpers/documentables_helper.rb
  app/helpers/imageables_helper.rb
  app/models/budget/investment.rb
  app/models/concerns/documentable.rb
  app/models/dashboard/action.rb
  app/models/image.rb
  app/models/legislation/process.rb
  app/models/legislation/proposal.rb
  app/models/milestone.rb
  app/models/poll/question/answer.rb
  app/models/proposal.rb
  app/models/setting.rb
  app/views/admin/settings/_content_types_settings_form.html.erb
  app/views/admin/settings/_featured_settings_form.html.erb
  app/views/admin/settings/_featured_settings_table.html.erb
  app/views/admin/settings/_filter_subnav.html.erb
  app/views/admin/settings/_images_and_documents_tab.html.erb
  app/views/admin/settings/_settings_form.html.erb
  app/views/admin/settings/_settings_table.html.erb
  app/views/admin/settings/index.html.erb
  config/i18n-tasks.yml
  config/locales/en/admin.yml
  config/locales/en/settings.yml
  config/locales/es/admin.yml
  config/locales/es/settings.yml
  config/routes/admin.rb
  spec/features/admin/settings_spec.rb
  spec/models/setting_spec.rb
  spec/shared/models/image_validations.rb
Labels: Backport Needed, Improvement, admin

#2032 Show name and email for deleted poll officer's user account
  app/models/poll/officer.rb
  config/locales/en/general.yml
  config/locales/es/general.yml
  spec/models/poll/officer_spec.rb
Labels: Bug

#2037 Don't show links to disabled budget results
  app/helpers/budgets_helper.rb
  app/views/budgets/_finished.html.erb
  app/views/budgets/_subnav.html.erb
  app/views/budgets/executions/show.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/results/show.html.erb
  app/views/budgets/show.html.erb
  app/views/budgets/stats/show.html.erb
  app/views/custom/budgets/index.html.erb
  spec/features/budgets/results_spec.rb
Labels: Backport Needed

#2035 Add task to upgrade to a new release
  config/deploy.rb
  lib/application_logger.rb
  lib/tasks/budgets.rake
  lib/tasks/consul.rake
  lib/tasks/settings.rake
  lib/tasks/stats.rake
  lib/tasks/stats_and_results.rake
Labels: Backport Needed

#2033 Add original heading id to investments
  app/models/budget/investment.rb
  db/migrate/20190531173316_add_original_heading_id_to_investments.rb
  db/schema.rb
  lib/tasks/budgets.rake
  spec/lib/tasks/budgets_spec.rb
  spec/models/budget/investment_spec.rb
Labels: Backport Needed, Budget, Rake

#2040 Avoid error when accessing final voting stats before the balloting phase
  app/controllers/admin/stats_controller.rb
  app/models/abilities/administrator.rb
  app/views/admin/stats/budgets.html.erb
  config/locales/en/admin.yml
  config/locales/es/admin.yml
  spec/features/admin/stats_spec.rb
Labels: Backport Needed, Bug, admin, stats

#2036 Remove system recounts in the admin section
  app/models/poll.rb
  app/views/admin/poll/booth_assignments/show.html.erb
  app/views/admin/poll/recounts/index.html.erb
  spec/factories/polls.rb
  spec/features/admin/poll/booth_assigments_spec.rb
  spec/features/admin/poll/polls_spec.rb
  spec/models/poll/poll_spec.rb
Labels: Backport Needed

#2038 Hide information on selected proposals
  app/assets/stylesheets/participation.scss
  app/views/custom/proposals/index.html.erb
  app/views/custom/proposals/show.html.erb
  app/views/proposals/_info.html.erb
  app/views/proposals/index.html.erb
  app/views/proposals/show.html.erb
  spec/features/proposals_spec.rb
Labels: Backport Needed

#2041 Add related content section on proposal dashboard
  app/assets/stylesheets/dashboard.scss
  app/controllers/dashboard_controller.rb
  app/helpers/proposals_dashboard_helper.rb
  app/views/dashboard/_menu.html.erb
  app/views/dashboard/related_content.html.erb
  config/locales/en/general.yml
  config/locales/es/general.yml
  config/routes/proposal.rb
  spec/features/dashboard/dashboard_spec.rb
Labels: Backport Needed

#2043 Avoid error for polls results
  app/models/poll/question.rb
  spec/features/polls/results_spec.rb
Labels: Bug, Proposals

#2042 Reset globalize fallbacks before every test
  spec/spec_helper.rb
Labels: upstream

#2045 Hide polls created by users on admin poll booth assigments
  app/controllers/admin/poll/polls_controller.rb
  spec/features/admin/poll/booth_assigments_spec.rb
Labels: Backport Needed
